### ISSUE TITLE
提交非视频文件

### ISSUE THREAD

**Issue by mefengxiao** [iPaperClipICU/ipaperclip.icu#119]
本人保存了 回形针PaperClip Vol.057 原子弹制造指南 这期视频微信公众号的资料，并且在本人的个人网盘中找到，想为ipaperclip.icu做一份贡献，其他资料由于年代久远未保存，抱歉

[低阻抗开关.pdf](https://github.com/user-attachments/files/17171799/default.pdf)
[电子雷管.pdf](https://github.com/user-attachments/files/17171800/default.pdf)
[分离铀-235的方法和仪器.pdf](https://github.com/user-attachments/files/17171801/-235.pdf)
[洛斯阿拉莫斯国家实验室.pdf](https://github.com/user-attachments/files/17171804/default.pdf)
[气压感应开关.pdf](https://github.com/user-attachments/files/17171805/default.pdf)
[生产、分离、浓缩钚.pdf](https://github.com/user-attachments/files/17171806/default.pdf)

顺带说一句，我很喜欢网站的风格，想用这种风格制作个人博客，能否教一下如何部署，或制作教程
本人第一次提交issues，不熟练使用github，可能投错地方了，如有错误，请指正，谢谢

**Comment by qiaoshouzi** [comment]
非常感谢您提供的文件

本网站使用 [Vue](https://cn.vuejs.org/) + [Naive UI](https://www.naiveui.com) 进行开发，并未使用博客站点生成工具，因此无法提供相关帮助。
